//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterSentials.Framework.EntLib.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("entersentialsstorage")]
        public string DefaultLoggingAzureInstanceName {
            get {
                return ((string)(this["DefaultLoggingAzureInstanceName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DefaultEndpointsProtocol=https;AccountName=entersentialsstorage;AccountKey=KrC1Iv" +
            "aaqqj9v8Pm+yNF3sNKmM/jYc30crOC1BNUTUKEbLFrUPsb0S8+DvLhr8gxP7s1xIFU+F1cDn2gHn9ljg" +
            "==")]
        public string DefaultLoggingAzureStorageAccountConnectionString {
            get {
                return ((string)(this["DefaultLoggingAzureStorageAccountConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SLABLogsTable")]
        public string DefaultLoggingAzureTableName {
            get {
                return ((string)(this["DefaultLoggingAzureTableName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AllowLoggingToAzureTable {
            get {
                return ((bool)(this["AllowLoggingToAzureTable"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AllowLoggingToWindowsEventLog {
            get {
                return ((bool)(this["AllowLoggingToWindowsEventLog"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Verbose")]
        public global::System.Diagnostics.Tracing.EventLevel DefaultLoggingEventLevel {
            get {
                return ((global::System.Diagnostics.Tracing.EventLevel)(this["DefaultLoggingEventLevel"]));
            }
        }
    }
}
