//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterSentials.Framework.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ShieldFromDataAccessExceptions")]
        public string ShieldFromDataAccessExceptionsExceptionPolicyName {
            get {
                return ((string)(this["ShieldFromDataAccessExceptionsExceptionPolicyName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ShieldFromBusinessLogicExceptions")]
        public string ShieldFromBusinessLogicExceptionsExceptionPolicyName {
            get {
                return ((string)(this["ShieldFromBusinessLogicExceptionsExceptionPolicyName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public string DefaultExceptionPolicyName {
            get {
                return ((string)(this["DefaultExceptionPolicyName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en-US")]
        public string Culture_EnglishUS_Name {
            get {
                return ((string)(this["Culture_EnglishUS_Name"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("application")]
        public string ApplicationConfigurationSectionName {
            get {
                return ((string)(this["ApplicationConfigurationSectionName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EnterSentials.Framework.Unity.UnityBasedComponents, EnterSentials.Framework.Unity" +
            "")]
        public string ComponentsProviderAssemblyQualifiedTypeName {
            get {
                return ((string)(this["ComponentsProviderAssemblyQualifiedTypeName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AuditableDomainObjectIsActiveOnCreation {
            get {
                return ((bool)(this["AuditableDomainObjectIsActiveOnCreation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShouldIncludeNoCacheHeaderForCors {
            get {
                return ((bool)(this["ShouldIncludeNoCacheHeaderForCors"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShouldIncludePreflightResponseMaxAgeHeaderForCors {
            get {
                return ((bool)(this["ShouldIncludePreflightResponseMaxAgeHeaderForCors"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3600")]
        public int PreflightResponseMaxAgeInSeconds {
            get {
                return ((int)(this["PreflightResponseMaxAgeInSeconds"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2147483647")]
        public int DotNetJsonSerializerMaxJsonLength {
            get {
                return ((int)(this["DotNetJsonSerializerMaxJsonLength"]));
            }
        }
    }
}
